# Generated by Django 4.0.4 on 2022-06-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0005_afisha_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
    ]
