# Generated by Django 4.0.4 on 2022-06-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0007_photo_alter_image_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afisha',
            options={'verbose_name': 'Афишу', 'verbose_name_plural': 'Афиши'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Сотрудника', 'verbose_name_plural': 'Труппа'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фотографию', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/users/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
