# Generated by Django 4.0.4 on 2022-06-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_album_photo_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='task',
            field=models.TextField(default='', verbose_name='Биография'),
        ),
    ]
